# Generated by Django 3.2.5 on 2021-07-18 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
